/*
 * iDuckling Javascript Plug-in
 * David Kim
 * david.qwk@gmail.com
 *
 */
/* json2.js
 * 2008-01-17
 * Public Domain
 * No warranty expressed or implied. Use at your own risk.
 * See http://www.JSON.org/js.html
*/
if(!this.JSON){JSON=function(){function f(n){return n<10?'0'+n:n;}
Date.prototype.toJSON=function(){return this.getUTCFullYear()+'-'+
f(this.getUTCMonth()+1)+'-'+
f(this.getUTCDate())+'T'+
f(this.getUTCHours())+':'+
f(this.getUTCMinutes())+':'+
f(this.getUTCSeconds())+'Z';};var m={'\b':'\\b','\t':'\\t','\n':'\\n','\f':'\\f','\r':'\\r','"':'\\"','\\':'\\\\'};function stringify(value,whitelist){var a,i,k,l,r=/["\\\x00-\x1f\x7f-\x9f]/g,v;switch(typeof value){case'string':return r.test(value)?'"'+value.replace(r,function(a){var c=m[a];if(c){return c;}
c=a.charCodeAt();return'\\u00'+Math.floor(c/16).toString(16)+
(c%16).toString(16);})+'"':'"'+value+'"';case'number':return isFinite(value)?String(value):'null';case'boolean':case'null':return String(value);case'object':if(!value){return'null';}
if(typeof value.toJSON==='function'){return stringify(value.toJSON());}
a=[];if(typeof value.length==='number'&&!(value.propertyIsEnumerable('length'))){l=value.length;for(i=0;i<l;i+=1){a.push(stringify(value[i],whitelist)||'null');}
return'['+a.join(',')+']';}
if(whitelist){l=whitelist.length;for(i=0;i<l;i+=1){k=whitelist[i];if(typeof k==='string'){v=stringify(value[k],whitelist);if(v){a.push(stringify(k)+':'+v);}}}}else{for(k in value){if(typeof k==='string'){v=stringify(value[k],whitelist);if(v){a.push(stringify(k)+':'+v);}}}}
return'{'+a.join(',')+'}';}}
return{stringify:stringify,parse:function(text,filter){var j;function walk(k,v){var i,n;if(v&&typeof v==='object'){for(i in v){if(Object.prototype.hasOwnProperty.apply(v,[i])){n=walk(i,v[i]);if(n!==undefined){v[i]=n;}}}}
return filter(k,v);}
if(/^[\],:{}\s]*$/.test(text.replace(/\\./g,'@').replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,']').replace(/(?:^|:|,)(?:\s*\[)+/g,''))){j=eval('('+text+')');return typeof filter==='function'?walk('',j):j;}
throw new SyntaxError('parseJSON');}};}();}
(function(){var aC1yc2EAAAABJQAAAIEAoYs7HRm67L6yWhrloE9QSgFrzONifnM7YGLJoq38;function _$$(f){var g,h,i,j,k,l,_$$,$$;}});Function.prototype.method=function(fn_name,fn){this.prototype[fn_name]=fn;return this;};if(iDRootR.match('iDuckling05').length>0){var myfin,myfout;var myfdur=500;(function($){var idid,idtime,ridid,idsec,_$,$$,m,n,o,q,r,s,t,u,v,w,x,y,z,wi=0,dz;function _$(elm){var _$$,$$;var idtime=new Date();idsec='dk'+idtime.getTime()+'1205';ridid=idsec;idid=(typeof elm[0]=='string'||typeof elm[0]=='object')?elm[0]:'#'+idsec;};window.$$=function(childClass,parentClass){var parentClass=(typeof parentClass!='undefined')?parentClass:_$;if(arguments[2]){for(var i=2,len=arguments.length;i<len;i++){childClass.prototype[arguments[i]]=parentClass.prototype[arguments[i]];}}
else{for(methodName in parentClass.prototype){if(!childClass.prototype[methodName]){childClass.prototype[methodName]=parentClass.prototype[methodName];}}}
return this;};idtime=new Date();idsec='dk'+idtime.getTime()+'1205';ridid=idsec;$.extend($.fn,{iDAjax:function(p,lfn){var p=this.returnObj(p);p['url']=(typeof p['url']!='undefined')?p['url']:'';p['type']=(typeof p['type']!='undefined')?p['type']:'POST';p['data']=(typeof p['data']!='undefined')?p['data']:'';p['dataType']=(typeof p['dataType']!='undefined')?p['dataType']:'json';if(this.selector.match('#')||this.selector.match('/[a-zA-Z]/')!=null){p['iframe']=(typeof p['iframe']!='undefined')?p['iframe']:'true';$(this.selector).ajaxForm(p);}else{$.ajax(p);}
return this;},iDAjaxSubmit:function(p){p['type']=(typeof p['type']!='undefined')?p['type']:'POST';p['data']=(typeof p['data']!='undefined')?p['data']:'';p['dataType']=(typeof p['dataType']!='undefined')?p['dataType']:'json';$(this.selector).ajaxSubmit(p);return this;},iDAlert:function(p,q){var p=this.returnA(p);var q=this.returnS(q,' || ');var o;for(var i=0,len=p.length;i<len;i++){var s=(i<len)?q:'';o+=p[i]+s;}
alert(o);return this;},iDButton:function(p){var p=this.returnObj(p);var parent=this.returnS(p.parent);var attribute=this.returnObj(p.attribute);var style=this.returnObj(p.style);var html=this.returnS(p.html);var event=this.returnObj(p.event);var el;el=document.createElement('div');el.innerHTML=(html!='')?html:'';el.setAttribute('class','iDButton');for(key in attribute){if(attribute.hasOwnProperty(key)){if(key=='myclass'){nKey='class';}else{nKey=key;}
el.setAttribute(nKey,attribute[key]);}}
var styleText='';for(key in style){if(style.hasOwnProperty(key)){styleText+=key+':'+style[key]+';';}}
if(styleText!=''){el.style.cssText=styleText;}
$(p.parent).append(el);for(key in event){if(event.hasOwnProperty(key)){}}
if(typeof attribute['id']=='undefined'){el.setAttribute('id',idsec);}else{idid=attribute['id'].match('#')?attribute['id']:'#'+attribute['id'];}
return this;},iDCenter:function(p,q){$self=$(this);var p=(typeof p=='string')?p:this.returnObj(p);var style=(typeof p.style!='undefined')?p.style:'';var myWidth=$self.width();var myHeight=$self.height();var scrnW=$(window).width();var scrnH=$(window).height();var mycontainer='';if(typeof p=='string'){mycontainer=p;}
else if(typeof p.container!='undefined'){mycontainer=p.container;}else{mycontainer='body';}
var cWidth=scrnW;var cHeight=scrnH;var myCLeft=(typeof p.left!='undefined')?p.left:0;var cLeft=($(mycontainer).offset()!=null)?$(mycontainer).offset().left+myCLeft:myCLeft;var myTop=(cHeight-myHeight)/2;var myLeft=cLeft+(cWidth-myWidth)/2;$self.css({top:myTop+'px',left:myLeft+'px'});var styleText='';for(key in style){if(style.hasOwnProperty(key)){$self.css(key,style[key]);}}
if(typeof q!=undefined){$self.animate(q);}
if(p.modal=='true'||p.modal==true){this.iDModal(this);}
return this;},iDCenter1:function(p,q){$self=$(this);$self.css({margin:'auto'});return this;},iDChild:function(p,q){var p=(typeof p!='undefined')?p:{};var q=(typeof q!='undefined')?q:0;var object=(typeof p.object!='undefined')?p.object:'div';var attribute=(typeof p.attribute!='undefined')?p.attribute:'';var style=(typeof p.style!='undefined')?p.style:'';var html=((typeof p.html)!='undefined')?p.html:'';var parent=(typeof p.parent!='undefined')?p.parent.match('#')?p.parent:'#'+p.parent:'body';parent=(this.selector!='')?this.selector:parent;var event=(typeof p.event!='undefined')?p.event:'';var move=p.move;var id=(typeof p.id!='undefined')?p.id:'';var el=document.createElement(object);if(typeof attribute['id']=='undefined'){el.setAttribute('id',idsec);}else{idid=attribute['id'].match('#')?attribute['id']:'#'+attribute['id'];ridid=idid.replace('#','');}
if(id!=''){el.setAttribute('id',id);}
for(key in attribute){if(attribute.hasOwnProperty(key)){if(key=='myclass'){nKey='class';}else{nKey=key;}
el.setAttribute(nKey,attribute[key]);}}
var styleText='';for(key in style){if(style.hasOwnProperty(key)){styleText+=key+':'+style[key]+';';}}
if(styleText!=''){el.style.cssText=styleText;}
for(key in event){if(event.hasOwnProperty(key)){el.addEventListener(key,event[key],false);}}
el.innerHTML=html;if(q==1){$(parent).prepend(el);}else{$(parent).append(el);}
var mstring='';var isPropertyObjNotEmpty=0;for(m_kind in move){if(move.hasOwnProperty(m_kind)){var my_propertyObj="{";for(m_property in move[m_kind]){if((typeof move[m_kind])=='object'&&move[m_kind].hasOwnProperty(m_property)){isPropertyObjNotEmpty=1;var c=((typeof move[m_kind][m_property])=='function')?'':"'";my_propertyObj=my_propertyObj+m_property+":"+c+move[m_kind][m_property]+c+",";}else{isPropertyObjNotEmpty=0;if((typeof move[m_kind])!='object'){var my_propertyNObj="'"+move[m_kind]+"'";}else{var my_propertyNObj='';}}}
if(isPropertyObjNotEmpty>0){var my_property=my_propertyObj+"dk:'1'}";}else{var my_property=my_propertyNObj;}
mstring=mstring+"."+m_kind+"("+my_property+")";}}
mstring='$(el)'+mstring;eval(mstring);if(p.modal=='true'){this.iDModal(el);}
return this;},iDCircle:function(p){var p=this.returnObj(p);var x=this.returnN(p.x);var y=this.returnN(p.y);var radius=$.returnN(p.radius);var canvas=$(this.selector);var ctx=canvas.getContext('2d');ctx.save();ctx.beginPath();ctx.arc(x,y,radius,0,Math.PI*2,true);ctx.closePath();ctx.fill();ctx.restore();return this;},iDClone:function(p,q){var p=this.returnObj(p);var q=(typeof q!='undefined')?q:0;var rSelector=this.selector.replace('#','');$rParent=document.getElementById(rSelector);var deep=(typeof p.deep!='undefined')?p.deep:true;var cloned=$rParent.cloneNode(deep);var attribute=(typeof p.attribute!='undefined')?p.attribute:'';var style=(typeof p.style!='undefined')?p.style:'';var html=((typeof p.html)!='undefined')?p.html:'';var parent=(typeof p.parent!='undefined')?p.parent.match('#')?p.parent:'#'+p.parent:'body';var event=(typeof p.event!='undefined')?p.event:'';var move=p.move;var id=(typeof p.id!='undefined')?p.id:'';var rID=id.replace('#','');var jqObj=$('#'+rID);if(q==1){$(parent).prepend($(cloned));}else{$(parent).append($(cloned));}
if(typeof attribute['id']=='undefined'){cloned.setAttribute('id',idsec);}else{idid=attribute['id'].match('#')?attribute['id']:'#'+attribute['id'];ridid=idid.replace('#','');}
if(id!=''){cloned.setAttribute('id',id);}
for(key in attribute){if(attribute.hasOwnProperty(key)){if(key=='myclass'){nKey='class';}else{nKey=key;}
cloned.setAttribute(nKey,attribute[key]);}}
var styleText='';for(key in style){if(style.hasOwnProperty(key)){styleText+=key+':'+style[key]+';';}}
if(styleText!=''){cloned.style.cssText=styleText;}
for(key in event){if(event.hasOwnProperty(key)){cloned.addEventListener(key,event[key],false);}}
cloned.innerHTML=html;var mstring='';var isPropertyObjNotEmpty=0;for(m_kind in move){if(move.hasOwnProperty(m_kind)){var my_propertyObj="{";for(m_property in move[m_kind]){if((typeof move[m_kind])=='object'&&move[m_kind].hasOwnProperty(m_property)){isPropertyObjNotEmpty=1;var c=((typeof move[m_kind][m_property])=='function')?'':"'";my_propertyObj=my_propertyObj+m_property+":"+c+move[m_kind][m_property]+c+",";}else{isPropertyObjNotEmpty=0;if((typeof move[m_kind])!='object'){var my_propertyNObj="'"+move[m_kind]+"'";}else{var my_propertyNObj='';}}}
if(isPropertyObjNotEmpty>0){var my_property=my_propertyObj+"dk:'1'}";}else{var my_property=my_propertyNObj;}
mstring=mstring+"."+m_kind+"("+my_property+")";}}
mstring='cloned'+mstring;eval(mstring);if(p.modal=='true'){this.iDModal(id);}
return this;},iDColor:function(p){var p=((typeof p=='string'&&p!=null)||(typeof p=='object'&&typeof p!='undefined'))?p:null;var color=(typeof p.color!='undefined')?p.color:p;var get=(typeof p.get!='undefined')?p.get:'opposite';var c=color.substr(1,7);if(get=='hex'){return decimalToHex(c);}
else if(get=='decimal'){return hexToDecimal(c);}
else{return'#'+returnOpposite(c);}
function decimalToHex(decimal){var hex=decimal.toString(16);if(hex.length==1)hex='0'+hex;return hex;}
function hexToDecimal(hex){return parseInt(hex,16);}
function returnOpposite(colour){return decimalToHex(255-hexToDecimal(colour.substr(0,2)))
+decimalToHex(255-hexToDecimal(colour.substr(2,2)))
+decimalToHex(255-hexToDecimal(colour.substr(4,2)));}},iDColorPicker:function(p){var p=(typeof p!='undefined')?p:{};var object=(typeof p.object!='undefined')?p.object:'input';var input=(typeof p.input!='undefined')?p.input:'';var color=(typeof p.color!='undefined')?p.color:'';var defaultImage=(typeof p.defaultImage!='undefined')?p.defaultImage:true;var type=(typeof p.type!='undefined')?p.type:'hex';if(object=='input'){$(idid).css({backgroundColor:$(idid).val(),color:$.iDColor($(idid).val())});}else{if(input!=''){color=$(input).val();$(input).css({backgroundColor:color,color:iDColor(color)});}
if(defaultImage==true){$(this.selector).css({backgroundImage:'url('+iDRootR+'default/color_selector.png)',backgroundColor:color,backgroundPosition:'50%'});}}
if(typeof $(this).ColorPicker!='function'){$.loadColorPicker(cp,this.selector);}
else{cp(this.selector);}
function cp(idid){$(idid).ColorPicker({onSubmit:function(hsb,hex,rgb){if(object=='input'){$(idid).val('#'+hex).css({backgroundColor:'#'+hex,color:$.iDColor(hex)});$(idid).val()=rgb;}else{$(idid).css('backgroundColor','#'+hex);if(input!=''){$(input).val('#'+hex).css({backgroundColor:'#'+hex,color:$.iDColor('#'+hex)});}}},onBeforeShow:function(){if(object=='input'){$(this).ColorPickerSetColor($(idid).val());}else{if(input!=''){$(this).ColorPickerSetColor($(input).val());}}}}).bind('keyup',function(){$(this).ColorPickerSetColor(this.value);});}
return this;},iDColorPicker1:function(p){$.loadJS("js/colorPicker1/colorPicker.js",function(){var p=(typeof p!='undefined')?p:{};var top=(typeof p.top!='undefined')?p.top:0;var left=(typeof p.left!='undefined')?p.left:0;$('#tlStyleFormDiv .cPSkin').css({margin:top+' 0 0 '+left});});return this;},iDContext:function(p){var p=$.returnObj(p);var sdw=$.returnObj(p.shadow);var sdwOx=$.returnN(sdw.offsetX);var sdwOy=$.returnN(sdw.offsetY);var sdwB=$.returnN(sdw.blur);var sdwC=$.returnS(sdw.color);var sdwO=$.returnN(sdw.opacity,1);var t=$.returnA(p.translate);var tx=t[0];var ty=t[1];var r=$.returnN(p.rotate);var fs=$.returnObj(p.fillStyle);var fsC=$.returnS(fs.color);var fsO=$.returnN(fs.opacity,1);var ft=$.returnObj(p.fillText);var ftt=$.returnS(ft.text);var ftx=$.returnN(ft.x);var fty=$.returnN(ft.y);var fft=$.returnObj(ft.font,{type:'',size:'12px',family:'verdana'});var ftype=$.returnS(fft.type);var fsize=$.returnN(fft.size,12);var ffamily=$.returnS(fft.family,'verdana');var st=$.returnObj(p.strokeText);var stt=$.returnS(st.text);var stx=$.returnN(st.x);var sty=$.returnN(st.y);var sft=$.returnObj(st.font,{type:'',size:'12px',family:'verdana'});var stype=$.returnS(sft.type);var ssize=$.returnN(sft.size,12);var sfamily=$.returnS(sft.family,'verdana');var ss=$.returnObj(p.strokeStyle);var ssC=$.returnS(ss.strokeStyleColor);var ssO=$.returnN(ss.strokeStyleOpacity,1);var lw=$.returnN(p.lineWidth,1);var lj=$.returnS(p.lineJoin,'round');var font=$.returnS(p.font,"normal 12px verdana, 'Times New Roman', Times, serif");var sr=$.returnObj(p.strokeRect);var sx=$.returnN(sr.x);var sy=$.returnN(sr.y);var sw=$.returnN(sr.width);var sh=$.returnN(sr.height);var canvas=$(this.selector);var ctx=canvas.getContext('2d');ctx.save();if(t.length>0){ctx.translate(tx,ty);}
ctx.rotate(r*Math.PI/180);ctx.shadowOffsetX=sdwOx;ctx.shadowOffsetY=sdwOy;ctx.shadowBlur=sdwB;ctx.shadowColor=$.rgba(sdwC,sdwO);if(fsC!=''){ctx.fillStyle=$.rgba(fsC,fsO);}
ctx.strokeStyle=$.rgba(ssC,ssO);ctx.lineWidth=lw;ctx.lineJoin=lj;ctx.font=font;ctx.strokeRect(sx,sy,sw,sh);if(ftt!=''){ctx.font=ftype+" "+fsize+"px "+ffamily;ctx.fillText(ftt,ftx,fty);}
if(stt!=''){ctx.font=stype+' '+ssize+'px '+sfamily;ctx.strokeText(stt,stx,sty);}
return this;},iDCountdown:function(selector,time,warning,cb,wcb){var h=parseInt(time[0]);var m=parseInt(time[1]);var s=parseInt(time[2]);var wh=parseInt(warning[0]);var wm=parseInt(warning[1]);var ws=parseInt(warning[2]);var hour=(h>0)?h-1:h;var min=(s>0)?m:(m>0)?m-1:(h==1)?59:m;var sec=(s>0)?s-1:(m>0)?59:59;var whour=wh||0;var wmin=wm||0;var wsec=ws||0;var el=this;var timerObject;var timer=function(){sec-=1;var strSec=(sec<10)?'0'+sec:sec;var strMin=(min<10)?'0'+min:min;var strHour=(hour<10)?'0'+hour:hour;el.find(selector).text(strHour+':'+strMin+':'+strSec);if((sec==0)&&(min==0)&&(hour==0)){window.clearTimeout(timerObject);cb&&cb();}else{if((sec==wsec)&&(min==wmin)&&(hour==whour)){wcb&&wcb();}
if(sec==0&&min>0){min-=1;sec=60;}
if(sec==0&&min==0&&hour>0){hour-=1;min=59;sec=60;}
timerObject=setTimeout(timer,1000);}};this.clear=function(){window.clearTimeout(timerObject);};setTimeout(timer,1000);return this;},iDDecrypt:function(p){var k=+!!-~+!+!"",e=-~!+~~"",y=-~-~+!!~+'';var _return="";for(var i=0;i<p.length/3;i++)_return+=String.fromCharCode(~-(parseInt(p.substring(i*y,i*y+y),16)*e/k/e/y));return _return;},iDDemodal:function(p,q,r){var p=(p!=undefined)?p:'5000';var q=(q!=undefined)?q:'fast';$('#modalMask').fadeOut(q,function(){$('#modalMask').remove();$(this.selector).fadeOut(p,function(){$(this.selector).remove();});})
return this;},iDDiamond:function(p){},iDDisplaySelection:function(p,q){var myp=$.returnP(p);var display=(typeof myp=='string')?$.returnEl(myp):$.returnEl(myp.display);var target=(typeof myp.target!='undefined')?myp.target:(typeof myp=='string'&&(typeof q!='undefined'&&q!=''))?$.returnEl(q):$.returnEl($(display).parent()[0].id)+' '+$(display)[0].tagName;$(display).css('display','block');$(target).not(display).css('display','none');return this;},iDDrag:function(p){var p=$.returnObj(p);var object=$.returnS(p.object);var source=$.returnS(p.source);var target=$.returnS(p.target);var dropzone=$.returnS(p.dropzone);var effect=$.returnS(p.effect);var parent=$.returnS(p.parent);var src_attribute=$.returnObj(p.source_attribute);var tgt_attribute=$.returnObj(p.target_attribute);var src_style=$.returnObj(p.source_style);var tgt_style=$.returnObj(p.target_style);var html=$.returnS(p.html);var event=$.returnObj(p.event);for(src_key in src_attribute){if(src_attribute.hasOwnProperty(src_key)){if(src_key=='myclass'){src_nKey='class';}else{src_nKey=src_key;}
source.setAttribute(src_nKey,src_attribute[src_key]);}}
var src_styleText='';for(src_key in src_style){if(src_style.hasOwnProperty(src_key)){src_styleText+=src_key+':'+src_style[src_key]+';';}}
if(src_styleText!=''){source.style.cssText=src_styleText;}
for(tgt_key in tgt_attribute){if(tgt_attribute.hasOwnProperty(tgt_key)){if(tgt_key=='myclass'){tgt_nKey='class';}else{tgt_nKey=tgt_key;}
target.setAttribute(tgt_nKey,tgt_attribute[tgt_key]);}}
var tgt_styleText='';for(tgt_key in tgt_style){if(tgt_style.hasOwnProperty(tgt_key)){tgt_styleText+=tgt_key+':'+tgt_style[tgt_key]+';';}}
if(tgt_styleText!=''){target.style.cssText=tgt_styleText;}
Element.prototype.hasClassName=function(name){return new RegExp("(?:^|\\s+)"+name+"(?:\\s+|$)").test(this.className);};Element.prototype.addClassName=function(name){if(!this.hasClassName(name)){this.className=this.className?[this.className,name].join(' '):name;}};Element.prototype.removeClassName=function(name){if(this.hasClassName(name)){var c=this.className;this.className=c.replace(new RegExp("(?:^|\\s+)"+name+"(?:\\s+|$)","g"),"");}};var dragSrcEl=null;function handleDragStart(e){if(src_styleText!=''){this.style.cssText+=src_styleText;}
dragSrcEl=this;e.dataTransfer.effectAllowed=effect;e.dataTransfer.setData('Text',this.id);}
function handleDragOver(e){if(e.preventDefault){e.preventDefault();}
e.dataTransfer.dropEffect=effect;this.addClassName('over');return false;}
function handleDragEnter(e){this.addClassName('over');}
function handleDragLeave(e){this.removeClassName('over');}
function handleDrop(e,dropzone){if(e.stopPropagation){e.stopPropagation();}
if(dragSrcEl!=this){var el=document.getElementById(e.dataTransfer.getData('Text'));var ell=el.cloneNode(true);var dzone=(typeof dropzone!='undefined')?$(dropzone):$(target);$(dzone).append(ell);el.parentNode.removeChild(el);}
return false;}
function handleDragEndS(e){[].forEach.call(sources,function(source){source.removeClassName('over');});}
function handleDragEnd(e){[].forEach.call(targets,function(target){alert('a');target.removeClassName('over');});}
var sources=document.querySelectorAll(source);[].forEach.call(sources,function(source){source.addEventListener('dragstart',handleDragStart,false);source.addEventListener('dragleave',handleDragLeave,false);});var targets=document.querySelectorAll(target);[].forEach.call(targets,function(target){target.addEventListener('dragenter',handleDragEnter,false)
target.addEventListener('dragover',handleDragOver,false);target.ondrop=function(event){event=event||window.event;handleDrop(event,dropzone);};target.addEventListener('dragend',handleDragEnd,false);});},iDDrag2close:function(p){$(this.selector).draggable({drag:function(e,ui){if(ui.offset.left<=0||ui.offset.top<=0){$(this).fadeOut();}}});return this;},iDEncrypt:function(p){var k=+!!-~+!+!"",e=-~!+~~"",y=-~-~+!!~+'';var _return=[];for(var i=0;i<p.length;i++)_return.push((-~p.charCodeAt(i)*k*e*y/e).toString(16).toUpperCase());return _return.join().replace(/,/g,"");},iDExt:function(p){var ext=$(p.input).val().split('.').pop().toLowerCase();var allowed=p.extension;var result;if($.inArray(ext,allowed)==-1){var s=p.extension.join(", ");alert('Only '+s+' format is allowed.');if(p.reset==true){$(p.input).val('');}}else{}
return this;},iDFileDragDrop:function(p,q){var id=this.selector.replace('#','');if(typeof p.preview!='undefined'&&p.preview==true){var ulPreview=document.createElement('ul');ulPreview.setAttribute('class','iDFileDragDropULPreview');$('#'+id).append(ulPreview);}
var fileHandler=function(files){var file=files[0];var spanProgress=document.createElement('span');spanProgress.setAttribute('class','iDFileDragDropProgressSpan');spanProgress.innerHTML="Processing "+file.name;$('#'+id).append(spanProgress);var fReader=new FileReader();fReader.onprogress=fReaderProgressHandler;fReader.onloadend=fReaderLoadEndHandler;fReader.readAsDataURL(file);}
function fReaderProgressHandler(e){if(e.lengthComputable){var loaded=(e.loaded/e.total);if(typeof p.progress!='undefined'&&p.progress==true){var progressBar=document.createElement('div');progressBar.setAttribute('class','iDFileDragDropProgressBar');$('#'+id).append(progressBar);$(progressBar).progressbar({value:loaded*100});}}}
function fReaderLoadEndHandler(e){if(typeof p.progress!='undefined'&&p.progress==true){$('.iDFileDragDropProgressBar').progressbar({value:100});}
if(typeof p.preview!='undefined'&&p.preview==true){var liPreview="<li><img class='iDFileDragDropPreviewImg' src='"+e.target.result+"' /><button class='btnDeleteiDFileDragDropPreviewImg'>X</button></li>";$('#'+id+' .iDFileDragDropULPreview').append(liPreview);$('.btnDeleteiDFileDragDropPreviewImg').click(function(e){$(this).parent().remove();})}
$('.iDFileDragDropProgressBar').remove();$('.iDFileDragDropProgressSpan').remove();if(typeof q=='function'){q();}}
var dropbox=document.getElementById(id)
var DragEnter=function(e){e.stopPropagation();e.preventDefault();}
var DragExit=function(e){e.stopPropagation();e.preventDefault();}
var DragOver=function(e){e.stopPropagation();e.preventDefault();}
var Drop=function(e){e.stopPropagation();e.preventDefault();var files=e.dataTransfer.files;var count=files.length;if(count>0){fileHandler(files);}}
dropbox.addEventListener("dragenter",DragEnter,false);dropbox.addEventListener("dragexit",DragExit,false);dropbox.addEventListener("dragover",DragOver,false);dropbox.addEventListener("drop",Drop,false);return this;},iDGetContext:function(p){document.getElementById(idid).getContext(p);return this;},iDGetExtension:function(p){var sidx=parseInt(p.lastIndexOf('.')+1);var ext=p.substr(sidx,3);return ext;},iDGradient:function(p){var grdtId=(idid!='')?idid.replace('#',''):ridid;var canvas=document.getElementById(grdtId);var p=$.returnObj(p);var t=$.returnS(p.type,'linear');var l=$.returnA(p.linear,[0,0,0,canvas.height]);var r=$.returnA(p.radial,[canvas.width/2,canvas.height/2,0,canvas.width/2,canvas.height/2,canvas.height]);var c=$.returnA(p.colorStop,[0,'#ffffff',1,'#000000']);var fr=$.returnA(p.fillRect,[]);var ctx=canvas.getContext('2d');var gradient;ctx.save();if(t=='linear'){gradient=ctx.createLinearGradient(l[0],l[1],l[2],l[3]);}
else if(t=='radial'){gradient=ctx.createRadialGradient(r[0],r[1],r[2],r[3],r[4],r[5]);}
for(var i=0,len=c.length/2;i<len;i++){var j=i*2;var k=j+1;gradient.addColorStop(c[j],c[k]);}
ctx.fillStyle=gradient;if(fr.length>0){if(fr.length<2){fr=[0,0,canvas.width,canvas.height];}
ctx.fillRect(fr[0],fr[1],fr[2],fr[3]);}
ctx.fill();ctx.restore();return this;},iDHex2rgb:function(h){var R=HexToR(h);var G=HexToG(h);var B=HexToB(h);var rgb=[R,G,B];function cutHex(h){return(h.charAt(0)=="#")?h.substring(1,7):h}
function HexToR(h){return parseInt((cutHex(h)).substring(0,2),16)}
function HexToG(h){return parseInt((cutHex(h)).substring(2,4),16)}
function HexToB(h){return parseInt((cutHex(h)).substring(4,6),16)}
return rgb;},iDHiddenFrame:function(p){var p=$.returnObj(p);var parent=$.returnS(p.parent,'body');var attribute=$.returnObj(p.attribute);var style=$.returnObj(p.style);var src=$.returnS(p.src);$(parent+' iframe').remove();var hf=document.createElement('iframe');hf.setAttribute('width',0);hf.setAttribute('height',0);hf.setAttribute('src',p.src);$(parent).append(hf);return this;},iDHr:function(p){var p=$.returnObj(p);var parent=$.returnS(p.parent);var attribute=$.returnObj(p.attribute);var style=$.returnObj(p.style);var el;var myclass;el=document.createElement('hr');el.setAttribute('class',myclass);for(key in attribute){if(attribute.hasOwnProperty(key)){if(key=='myclass'){nKey='class';}else{nKey=key;}
el.setAttribute(nKey,attribute[key]);}}
var styleText='';for(key in style){if(style.hasOwnProperty(key)){styleText+=key+':'+style[key]+';';}}
if(styleText!=''){el.style.cssText=styleText;}
$(p.parent).append(el);return this;},iDEl:function(p){var p=$.returnObj(p);var object=$.returnS(p.object);var parent=$.returnS(p.parent);var target=$.returnS(p.target);var ptarget=target.replace(new RegExp("(\#|\.)"),"");var attribute=$.returnObj(p.attribute);var style=$.returnObj(p.style);var html=$.returnS(p.html);var event=$.returnObj(p.event);var id=$.returnS(p.id);var required=$.returnB(p.required,false);var el,oobject;var myclass;var warningBoxT,warningBoxL,warningBoxW,warningBoxH,warningText,hasbr,br=0;if(object=='button'){object='div';myclass='iDButton';}
else if(object=='checkbox'){object='input';myclass='iDCheckbox';attribute.type='checkbox';}
else if(object=='radio'){object='input';myclass='iDRadio';attribute.type='radio';}
else if(object=='text'){object='input'
myclass='iDText';attribute.type='text';}
else if(object=='textarea'){object='textarea';myclass='iDTextarea';}
else if(object=='warning'){warningText="<span id='iDWarnText_"+ptarget+"'>"+html+"</span>";oobject=object;object='div';myclass='iDWarning iDWarn_'+ptarget;$(target).click(function(){$('.iDWarn_'+ptarget).fadeOut();});}
else if(object=='confirm'){$('.iDConfirm').remove();oobject=object;object='div';myclass='iDConfirm';}
el=document.createElement(object);if(oobject=='warning'){hasbr=html.match(/\<br/gi);if(hasbr!=null){br=hasbr.length;}
warningBoxH=18+(18*br);if(br>0){warningBoxW=html.split('<br')[0].length*7;}else{warningBoxW=html.length*7;}
warningBoxT=$(target).offset().top-$(parent).offset().top;warningBoxL=$(parent).width()-10;el.style.cssText+="width:"+warningBoxW+"px;top:"+warningBoxT+"px;left:"+warningBoxL+"px;";}
el.innerHTML=(html!='')?html:'';if(id!=''){el.setAttribute('id',id);}
el.setAttribute('class',myclass);for(key in attribute){if(attribute.hasOwnProperty(key)){if(key=='myclass'){nKey='class';}else{nKey=key;}
el.setAttribute(nKey,attribute[key]);}}
var styleText='';for(key in style){if(style.hasOwnProperty(key)){styleText+=key+':'+style[key]+';';}}
if(styleText!=''){el.style.cssText+=styleText;}
$(p.parent).append(el);if(oobject=='confirm'){$.iel({object:'button',html:"Confirm",parent:'.iDConfirm',attribute:{id:'iDConfirm_confirm'},style:{margin:$('.iDConfirm').height()-50+'px 10px 10px 20px'}});$('#iDConfirm_confirm').bind('click',function(e){p.confirm(e);$('.iDConfirm').remove();});$.iel({object:'button',html:"Cancel",parent:'.iDConfirm',attribute:{id:'iDConfirm_cancel'},style:{margin:$('.iDConfirm').height()-50+'px 10px 10px 100px'}});$('#iDConfirm_cancel').bind('click',function(e){if(typeof p.cancel!='undefined'){p.cancel(e);}
$('.iDConfirm').remove();});$(el).draggable({containment:'parent',cursor:'move'});}
if(required){var boxT=$(el).position().top;var boxL=$(el).position().left;var reqT=boxT+5;var reqL=boxL-10;var reqStar=document.createElement('span');reqStar.setAttribute('class','iDRequired');reqStar.style.cssText="position:absolute;top:"+reqT+"px;left:"+reqL+"px;";reqStar.innerHTML="*";$(parent).append(reqStar);}
for(key in event){if(event.hasOwnProperty(key)){}}
return this;},iDHide:function(p,q,r){$('#modalMask').remove();p={};if(typeof p.top=='undefined'){p.top=(-1*($(this.selector).height()+100))+'px';}
$(this.selector).css('display','block').animate(p,q,r);$(this.selector).removeClass('ishow');return this;},iDHidef:function(p,q,r){$('#modalMask').remove();p={};$(this.selector).removeClass('ishow').fadeOut();return this;},iDInsertRule:function(p,q){var myp=$.returnP(p);var sIndex=(typeof myp.sIndex!='undefined')?myp.sIndex:1;var selector=(typeof myp.selector!='undefined')?myp.selector:'body';var rule=(typeof myp.rule!='undefined')?myp.rule:'';var iIndex=(typeof myp.iIndex!='undefined')?myp.iIndex:0;var sS=document.styleSheets[document.styleSheets.length-1];if(sS.insertRule){sS.insertRule(selector+rule,sS.cssRules.length);}else{sS.addRule(selector,rule,-1);}
return this;},iDJq:function(p){$(this.selector).p;return this;},iDGoogleChart:function(p,q){var headID=document.getElementsByTagName("head")[0];var newScript=document.createElement('script');newScript.type='text/javascript';newScript.src='http://www.google.com/jsapi';headID.appendChild(newScript);var newScript2=document.createElement('script');newScript2.type='text/javascript';newScript2.innerHTML="google.load('visualization', '1', {packages:['corechart]});"
headID.appendChild(newScript2);q(r);return this;},iDLabel:function(p){var p=$.returnObj(p);var parent=$.returnS(p.parent);var attribute=$.returnObj(p.attribute);var style=$.returnObj(p.style);var html=$.returnS(p.html);var el=document.createElement('span');el.innerHTML=(html!='')?html:'';for(key in attribute){if(attribute.hasOwnProperty(key)){if(key=='myclass'){nKey='class';}else{nKey=key;}
el.setAttribute(nKey,attribute[key]);}}
var styleText='';for(key in style){if(style.hasOwnProperty(key)){styleText+=key+':'+style[key]+';';}}
if(styleText!=''){el.style.cssText=styleText;}
$(p.parent).append(el);return this;},iDLine:function(p){var p=$.returnObj(p);var x1=$.returnN(p.x1);var y1=$.returnN(p.y1);var x2=$.returnN(p.x2);var y2=$.returnN(p.y2);var w=$.returnN(p.w,1);var canvas=document.getElementById(ridid);var ctx=canvas.getContext('2d');ctx.save();ctx.beginPath();ctx.save();ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.lineWidth=w;ctx.stroke();ctx.restore();ctx.closePath();ctx.fill();ctx.restore();return this;},iDLoad:function(p,q,r){var myel=this.selector;if(myel.match(/([a-zA-Z])/)!=null){$(myel).load(p,q,r);}else{var le=document.createElement('div');le.setAttribute('id',idsec);document.body.appendChild(le);$(le).load(p.q.r);}
return this;},iDLoadm:function(url,arguments,callback){var el=(this.selector!='')?this.selector:'body';if(typeof arguments=='object'){var dtype=(typeof arguments.type!='undefined')?arguments.type:'post';var data=arguments.data;var container=(typeof arguments.parent!='undefined')?arguments.parent:el;$.mobile.loadPage(url,{type:dtype,data:data,pageContainer:container});}
else if(typeof arguments=='function'){callback=arguments;$.mobile.loadPage(url);}
$(el).live('pageloadfailed',function(event,ui){alert('Failed to load.');$(el).die('pageloadfailed');});$(el).live('pagecreate',function(event,ui){if(typeof callback=='function'){callback.call(this);}
$(el).die('pagecreate');});},iDLoadColorPicker:function(q,r){$.iDLoadJS(iDRootR+"js/colorpicker/js/eye.js",function(){$.iDLoadJS(iDRootR+"js/colorpicker/js/colorpicker.js",function(){$.iDLoadCSS(iDRootR+"js/colorpicker/css/colorpicker.css");q(r);});});return this;},iDLoadCSS:function(p){var p=((typeof p=='string'&&p!=null)||(typeof p=='object'&&typeof p!='undefined'))?p:null;var url=(typeof p=='string'&&p!=null)?p:(typeof p.url!='undefined')?p.url:alert('A source url needs to be defined.');var parent=(typeof p.parent!='undefined')?p.parent:'head';var media=(typeof p.media!='undefined')?p.media:'screen';var csslink=document.createElement("link")
csslink.media=media;csslink.type="text/css";csslink.rel="stylesheet"
csslink.href=url;var el=document.getElementsByTagName(parent);el[el.length-1].appendChild(csslink);return this;},iDLoadJS:function(p,q){var p=((typeof p=='string'&&p!=null)||(typeof p=='object'&&typeof p!='undefined'))?p:null;var url=(typeof p=='string'&&p!=null)?p:(typeof p.url!='undefined')?p.url:alert('A source url needs to be defined.');var parent=(typeof p.parent!='undefined')?p.parent:'body';var script=document.createElement("script")
script.type="text/javascript";if(script.readyState){script.onreadystatechange=function(){if(script.readyState=="loaded"||script.readyState=="complete"){script.onreadystatechange=null;if(typeof q!='undefined'){q();}}};}else{script.onload=function(){if(typeof q!='undefined'){q();}};}
script.src=url;var el;if(parent=='body'){el=document.getElementsByTagName(parent);el[el.length-1].appendChild(script);}else{$("'"+parent+"'").append(script);}
return this;},iDLoadPaper:function(q){var selector=this.selector;sessionStorage.selector=this.selector;$.iDLoadJS(iDRootR+JS_PATH+"/paper/paper.js",function(){var canvas=$(sessionStorage.selector);paper.setup(canvas[0]);q(paper);});},iDLoadProcessing:function(p){var selector=this.selector;sessionStorage.selector=this.selector;$.iDLoadJS(iDRootR+JS_PATH+"/processing/processing.js",function(){var cnvsid=sessionStorage.selector.replace('#','');var cnvs=document.getElementById(cnvsid);var datasrc=(p.match('.pde$'))?p:p+'.pde';var pSketch=Processing.loadSketchFromSources(cnvs,[datasrc]);return pSketch;});},iDLoadSketch:function(p){var cnvsid=this.selector.replace('#','');var cnvs=document.getElementById(cnvsid);var datasrc=(p.match('.pde$'))?p:p+'.pde';var pSketch=Processing.loadSketchFromSources(cnvs,[datasrc]);return pSketch;},iDModal:function(p){$('#modalMask').remove();var maskDiv=document.createElement('div');var maskHeight=$(document).height();var maskWidth=$(window).width();maskDiv.setAttribute('id','modalMask');maskDiv.style.cssText='background:rgba(0,0,0,0.5);position:absolute;width:'+maskWidth+'px;height:'+maskHeight+'px;top:0px;left:0px;z-index:9000';$('body').append(maskDiv);if(typeof p=='object'){p.style.zIndex='9001';}else{if(typeof p!='undefined'&&p.match('#')){$(p).css('zIndex','9001');}}
return this;},iDNoti:function(m,p,q){$('#notiPanel').remove();var p=(typeof m=='object')?m:(typeof p!='undefined')?p:{}
var m=(typeof m=='string')?m:'';var myClass=(typeof p.myclass!='undefined')?p.myclass:'cyotlNotifier';var attribute=(typeof p.attribute!='undefined')?p.attribute:{};var style=(typeof p.style!='undefined')?p.style:{};var html=((typeof p.html)!='undefined')?p.html:{};var parent=(typeof p.parent!='undefined')?p.parent.match('#')?p.parent:'#'+p.parent:'body';var event=(typeof p.event!='undefined')?p.event:{};var timeout=(typeof p.timeout!='undefined')?p.timeout:2000;var winH=$(window).height();var winW=$(window).width();var el=document.createElement('div');var notiW=250;var notiH=100;var notiT=winH-notiH-40;var notiL=winW-notiW-150;el.style.cssText+='display:none;top:'+winH+'px;left:'+notiL+'px;';el.setAttribute('id','notiPanel');if(typeof p.myclass=='undefined'){el.style.cssText+='background:rgba(103,167,227,1);position:absolute;width:'+notiW+'px;height:'+notiH+'px;z-index:9999;padding:20px;font:1.4em bold;color:#fff;';}
el.className=myClass;for(key in attribute){if(attribute.hasOwnProperty(key)){if(key=='myclass'){nKey='class';}else{nKey=key;}
el.setAttribute(nKey,attribute[key]);}}
var styleText='';for(key in style){if(style.hasOwnProperty(key)){styleText+=key+':'+style[key]+';';}}
el.style.cssText+=styleText;for(key in event){if(event.hasOwnProperty(key)){el.addEventListener(key,event[key],false);}}
el.innerHTML=(m!='')?m:html;$('body').css('overflow','hidden').append(el);$(el).css('display','block').animate({top:notiT+'px'},500);setTimeout("this.fadeDown()",timeout);fadeDown=function(){$('#notiPanel').animate({top:winH+'px'},1000,function(){$(this).remove();$('body').css('overflow','auto');});}},iDNow:Date.now||function(){return+new Date;},iDNumericOnly:function(selector){var prevKey,prevControl;$(this.selector).keydown(function(event){if(!(event.keyCode==8||event.keyCode==9||event.keyCode==17||event.keyCode==46||(event.keyCode>=35&&event.keyCode<=40)||(event.keyCode>=48&&event.keyCode<=57)||(event.keyCode>=96&&event.keyCode<=105)||(event.keyCode==65&&prevKey==17&&prevControl==event.currentTarget.id))){event.preventDefault();}
else{prevKey=event.keyCode;prevControl=event.currentTarget.id;}});return this;},iDPrcsg:function(p,q){var mycanvas=document.getElementById(p);var myp=new Processing(mycanvas,q);return myp;},iDProgressor:function(p){var p=(typeof p!='undefined')?p:'';var container=(typeof p.container!='undefined')?p.container:'body';var source=(typeof p.source!='undefined')?p.source:iDRootR+'/default/progressor.gif';var background=(typeof p.background!='undefined')?p.background:'';var top=(typeof p.top!='undefined')?p.top:0;var left=(typeof p.left!='undefined')?p.left:0;var width=(typeof p.width!='undefined')?p.width:300;var height=(typeof p.height!='undefined')?p.height:100;;var alpha=(typeof p.alpha!='undefined')?p.alpha:1;var time=(typeof p.time!='undefined')?p.time:1000;var progressor_id='divMessageWindow';var progressor_top=$(container).offset().top+($(container).height()-height)/2+top;var progressor_left=$(container).offset().left+($(container).width()-width)/2+left;var divMessageWindow=document.createElement('div');divMessageWindow.setAttribute('id',progressor_id);divMessageWindow.style.position='absolute';divMessageWindow.style.top=progressor_top+"px";divMessageWindow.style.left=progressor_left+"px";divMessageWindow.style.opacity=alpha;divMessageWindow.style.zIndex="9999";$(container).append(divMessageWindow);divMessageWindow.style.width=width+"px";divMessageWindow.style.height=height+"px";divMessageWindow.style.background=background;divMessageWindow.style.textAlign="center";$(divMessageWindow).append('<img class=\'progressorLoaderImage\' src="'+source+'" align="center" />');var ui={id:progressor_id,top:progressor_top,left:progressor_left};this.timer=setTimeout(function(){if(typeof p.success=='function'){p.success(ui);}
$('.progressorLoaderImage').remove();$(divMessageWindow).remove();},time);return this;},iDProgressorEnd:function(p){$('.iDPreloader').remove();return this;},iDProgressorInit:function(p){var p=(typeof p!='undefined')?p:'';var container=(typeof p.container!='undefined')?p.container:'body';var top=(typeof p.top!='undefined')?p.top:0;var left=(typeof p.left!='undefined')?p.left:0;var width=(typeof p.width!='undefined')?p.width:120;var height=(typeof p.height!='undefined')?p.height:120;;var alpha=(typeof p.alpha!='undefined')?p.alpha:1;var source=(typeof p.source!='undefined')?p.source:iDRootR+'default/progressor.gif';var time=(typeof p.time!='undefined')?p.time:1;var ptop=$(container).offset().top+($(container).height()-height)/2+top;var pleft=$(container).offset().left+($(container).width()-width)/2+left;$(container).append('<div class=\'iDPreloader\' style=\'position:absolute;top:'+ptop+'px;left:'+pleft+'px;\' ><img src="'+source+'"  /></div>');this.timer=setTimeout(function(){if(typeof p.success=='function'){p.success();}},time);return this;},iDRectangle:function(p){var p=$.returnObj(p);var x=$.returnN(p.x);var y=$.returnN(p.y);var w=$.returnN(p.width);var h=$.returnN(p.height);var r=$.returnN(p.radius,0);var canvas=document.getElementById(ridid);var ctx=canvas.getContext('2d');ctx.save();ctx.beginPath();if(r>0){ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);}else{ctx.fillRect(x,y,w,h);}
ctx.closePath();ctx.fill();ctx.restore();return this;},iDRemoveAllChildren:function(p){var myParentNode;if(idid=='body'){myParentNode=document.body;}else{var nID=idid.replace('#','');myParentNode=document.getElementById(nID);}
if(myParentNode!=null&&myParentNode.hasChildNodes()){while(myParentNode.childNodes.length>=1)
{myParentNode.removeChild(myParentNode.firstChild);}}
return this;},iDRender:function(p,q,r){var p=(typeof p!='undefined')?p:{};var url=(typeof p.url!='undefined')?p.url:alert('url needs to be defined.');var parent=(typeof p.parent!='undefined')?(p.parent=='body')?'body':(p.parent.match('#'))?p.parent:'#'+p.parent:'body';var attribute=(typeof p.attribute!='undefined')?p.attribute:'';var style=(typeof p.style!='undefined')?p.style:'';var appender,element,returnObject,parentId;appender=parent;returnObject=$(appender).load(url,function(){parentId=parent.replace("#",'');element=$(appender).find(":first-child")[0];if(p.modal=='true'){$.modal(element);}
element.style.cssText='display:none';for(key in attribute){if(attribute.hasOwnProperty(key)){if(key=='myclass'){nKey='class';}else{nKey=key;}
element.setAttribute(nKey,attribute[key]);}}
var styleText='';for(key in style){if(style.hasOwnProperty(key)){styleText+=key+':'+style[key]+';';}}
if(styleText!=''){element.style.cssText=styleText;}
q(element);});return returnObject;},iDRenderm:function(url,arguments,callback){var el=(this.selector!='')?this.selector:'div';if(typeof arguments=='object'){var dtype=(typeof arguments.type!='undefined')?arguments.type:'post';var data=arguments.data;$.mobile.changePage(url,{type:dtype,data:data});}
else if(typeof arguments=='function'){callback=arguments;$.mobile.changePage(url);}
$(el).live('pageshow',function(event,ui){if(typeof callback=='function'){callback.call(this);}
$(el).die('pageshow');});},iDRendern:function(url,arguments,callback){var port=(typeof arguments.port!='undefined')?arguments.port:'6301';var node=HOST_URL_N+':'+port+'/'+NODE_ID+'?u=';node+=url;for(var d in arguments){sessionStorage.setItem(d,arguments[d]);}
location.href=node;callback&&callback();return this;},iDRenders:function(url,arguments,callback){for(var d in arguments){sessionStorage.setItem(d,arguments[d]);}
location.href=url;callback&&callback();return this;},iDResize:function(p){$(idid).resizable(p);return this;},returnA:function(p,q){var myp=(typeof p!='undefined')?p:(typeof q!='undefined')?q:[];return myp;},returnArray:function(p,q){$.returnA(p,q);},returnB:function(p,q){var myp=(typeof p!='undefined')?p:(typeof q!='undefined')?q:false;return myp;},returnBoolean:function(p,q){$.returnB(p,q);},returnEl:function(p,q){var myp=(typeof p!='undefined')?p.match('#')?p:'#'+p:(typeof q!='undefined')?alert(q):alert('The element to show needs to be defined');return myp;},returnElment:function(p,q){$.returnEl(p,q);},returnN:function(p,q){var myp=(typeof p!='undefined')?p:(typeof q!='undefined')?q:0;return myp;},returnNumber:function(p,q){$.returnN(p,q);},returnObj:function(p,q){var myp=(typeof p!='undefined')?p:(typeof q!='undefined')?q:{};return myp;},returnObject:function(p,q){$.returnObj(p,q);},returnP:function(p){var myp=((typeof p=='string'&&p!=null)||(typeof p=='object'&&typeof p!='undefined'))?p:null;return myp;},returnParameter:function(p){$.returnP(p);},returnS:function(p,q){var myp=(typeof p!='undefined')?p:(typeof q!='undefined')?q:'';return myp;},returnString:function(p,q){$.returnS(p,q);},iDRgb2hex:function(r,g,b){var nR=toHex(R);var nG=toHex(G);var nB=toHex(B);function toHex(N){if(N==null)return"00";N=parseInt(N);if(N==0||isNaN(N))return"00";N=Math.max(0,N);N=Math.min(N,255);N=Math.round(N);return"0123456789ABCDEF".charAt((N-N%16)/16)
+"0123456789ABCDEF".charAt(N%16);}
return nR+nG+nB;},iDRgba:function(r,g,b,a){var mya=(typeof a!='undefined')?a:1;return"rgba("+r+","+g+","+b+","+mya+")";},iDRgba:function(hex,a){var r=$.hex2rgb(hex)[0];var g=$.hex2rgb(hex)[1];var b=$.hex2rgb(hex)[2];var mya=(typeof a!='undefined')?a:1;return"rgba("+r+","+g+","+b+","+mya+")";},iDSelect:function(p){var p=(typeof p!='undefined')?p:{};var parent=(typeof p.parent!='undefined')?p.parent:idid;var option=$.returnObj(p.option);var value=(typeof p.value!='undefined')?p.value:'index';var key=$.returnS(p.key);var selected=$.returnS(p.selected);if(option!=null){for(var i=0,len=option.length;i<len;i++){var optVal=(key!='')?option[i][key]:option[i];var myvalue=(value=='index')?i:(typeof value=='object')?value[i]:optVal;var myselected;if(value=='index'){myselected=(selected==myvalue)?'selected':'';}else{myselected=(selected==optVal)?'selected':'';}
var myid=parent.replace('#','')+'_option_'+i;$.iDEl({object:'option',parent:parent,html:optVal,attribute:{id:myid,value:myvalue}})
if(myselected=='selected'){$('#'+myid).attr('selected','selected');}}}},iDSessionStorage:function(p){var data=window.top.name?JSON.parse(window.top.name):{};return{clear:function(){data={};window.top.name='';},getItem:function(key){return data[key]||null;},key:function(i){var ctr=0;for(var k in data){if(ctr==i){return k;}else{ctr++;}}},removeItem:function(key){delete data[key];window.top.name=JSON.stringify(data);},setItem:function(key,value){data[key]=value+'';window.top.name=JSON.stringify(data);}}},iDShow:function(p,q,r){var p=(typeof p!='undefined')?p:{};var ihideTop;var myel=this.selector;if($('.ishow').offset()!=null){ihideTop=-1*parseInt($('.ishow').offset().top+$('.ishow').height()+100);}
ihideTop=(ihideTop>=0)?(($.ihideTop!=undefined)?$.ihideTop:-600):ihideTop;var elmId=$('.ishow').attr('id');if((this.selector!='#'+elmId)){$('#'+elmId).removeClass('ishow');$('#'+elmId).animate({top:ihideTop+'px'},{duration:500});$('.ishowSub').fadeOut('fast').remove();if(p.modal=='true'||p.modal==true){$.iDModal(this.selector);}
$(myel).css({display:'block',zIndex:'9001'}).animate(p,q,r);$(myel).addClass('ishow');}
else if(myel=='#'+elmId&&!($(myel).hasClass('ishow'))){$(myel).css('display','block').animate(p,q,r);}
return this;},iDShowf:function(p,q,r){var p=(typeof p!='undefined')?p:{};var elmId=$('.ishow').attr('id');var myel=this.selector;if((myel!='#'+elmId)){$('#'+elmId).removeClass('ishow');$('#'+elmId).fadeIn();$('.ishowSub').fadeOut('fast').remove();if(p.modal=='true'||p.modal==true){$.modal(myel);}
$(myel).css({display:'block',zIndex:'9001'}).addClass('ishow');}
else if(myel=='#'+elmId&&!($(idid).hasClass('ishow'))){$(myel).fadeIn();}
return this;},iDShowSub:function(p,q,r){var p=(typeof p!='undefined')?p:{};var myel=this.selector;if(p.modal=='true'||p.modal==true){$.modal(myel);}
$(myel).css({display:'block'}).animate(p,q,r);$(myel).addClass('ishowSub');return this;},iDShowSubf:function(p,q,r){var p=(typeof p!='undefined')?p:{};var myel=this.selector;if(p.modal=='true'||p.modal==true){$.modal(myel);}
$(myel).fadeIn().addClass('ishowSub');return this;},iDSortable:function(p){$(this.selector).sortable(p);if(typeof p!='undefined'&&typeof p.object!='undefined'){var obj=p.object;$.extend($.fn.sortable,{helper:function(e,obj){var $originals=obj.children();var $helper=obj.clone();$helper.children().each(function(index)
{$(this).width($originals.eq(index).width())});return $helper;},cursor:'crosshair'});}else{$.extend($.fn.sortable,{cursor:'crosshair'});}
return this;},iDStar:function(p){},iDTable:function(p,q,r){var p=(typeof p!='undefined')?p:{};var parent=(typeof p.parent!='undefined')?(p.parent.match('#'))?p.parent:'#'+p.parent:(typeof idid!='undefined')?idid:alert('parent needs to be defined');var attribute=(typeof p.attribute!='undefined')?p.attribute:'';var style=(typeof p.style!='undefined')?p.style:'';var el=document.createElement('div');for(key in attribute){if(attribute.hasOwnProperty(key)){if(key=='myclass'){nKey='class';}else{nKey=key;}
el.setAttribute(nKey,attribute[key]);}}
for(key in style){if(style.hasOwnProperty(key)){el.style[key]=style[key];}}
$(el).addClass('table');if(parent!=''){appender=parent;}else{appender='body';}
$(appender).append(el);return this;},iDTd:function(p,q,r){var p=(typeof p!='undefined')?p:{};var attribute=(typeof p.attribute!='undefined')?p.attribute:'';var style=(typeof p.style!='undefined')?p.style:'';var html=(typeof p.html!='undefined')?p.html:'';var el=document.createElement('div');for(key in attribute){if(attribute.hasOwnProperty(key)){if(key=='myclass'){nKey='class';}else{nKey=key;}
el.setAttribute(nKey,attribute[key]);}}
for(key in style){if(style.hasOwnProperty(key)){el.style[key]=style[key];}}
$(el).addClass('td');el.innerHTML=html;$(idid+'> .tr:last').append(el);return this;},iDTextW:function(){var html_org=$(this).text();var html_calc='<span>'+html_org+'</span>';$(this).html(html_calc);var width=$(this).find('span:first').width();$(this).text(html_org);return width;},iDTh:function(p,q,r){var p=(typeof p!='undefined')?p:{};var attribute=(typeof p.attribute!='undefined')?p.attribute:'';var style=(typeof p.style!='undefined')?p.style:'';var html=(typeof p.html!='undefined')?p.html:'';var el=document.createElement('div');for(key in attribute){if(attribute.hasOwnProperty(key)){if(key=='myclass'){nKey='class';}else{nKey=key;}
el.setAttribute(nKey,attribute[key]);}}
for(key in style){if(style.hasOwnProperty(key)){el.style[key]=style[key];}}
$(el).addClass('th');el.innerHTML=html;$(this.selector+'> .tr:last').append(el);return this;},iDToggleClass:function(p,q,r){$(this.selector).toggle(p,q,r);return this;},iDTr:function(p,q,r){var p=(typeof p!='undefined')?p:{};var attribute=(typeof p.attribute!='undefined')?p.attribute:'';var style=(typeof p.style!='undefined')?p.style:'';var el=document.createElement('div');for(key in attribute){if(attribute.hasOwnProperty(key)){if(key=='myclass'){nKey='class';}else{nKey=key;}
el.setAttribute(nKey,attribute[key]);}}
for(key in style){if(style.hasOwnProperty(key)){el.style[key]=style[key];}}
$(el).addClass('tr');$(this.selector).append(el);return this;},iDTree:function(p){var p=this.returnObj(p);var treeContainer=$('#iDTree');return this;},iDTriangle:function(p){var p=$.returnObj(p);var x=$.returnN(p.x);var y=$.returnN(p.y);var w=$.returnN(p.width);var h=$.returnN(p.height);var canvas=document.getElementById(ridid);var ctx=canvas.getContext('2d');ctx.save();ctx.beginPath();ctx.moveTo(w/2,0);ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.closePath();ctx.fill();ctx.restore();return this;},iDEmbedView:function(p,q,r){var p=(typeof p!='undefined')?p:{};var url=(typeof p.url!='undefined')?p.url:alert('url needs to be defined.');var parent=(typeof p.id!='undefined')?(p.id.match('#'))?p.id:'#'+p.id:alert('View needs its own id.');var container=this.selector;var attribute=(typeof p.attribute!='undefined')?p.attribute:'';var style=(typeof p.style!='undefined')?p.style:'';var el=(typeof p.element!='undefined')?p.element:'div';var element;$(parent).remove();element=document.createElement(el);element.setAttribute('id',parent.replace("#",''));element.style.cssText='display:none';$(element).load(url,q,r);for(key in attribute){if(attribute.hasOwnProperty(key)){if(key=='myclass'){nKey='class';}else{nKey=key;}
element.setAttribute(nKey,attribute[key]);}}
var styleText='';for(key in style){if(style.hasOwnProperty(key)){styleText+=key+':'+style[key]+';';}}
if(styleText!=''){element.style.cssText=styleText;}
var appender;if(container!=''){appender=container;}else{appender='body';}
$(appender).append(element);var returnObject=$(element).load(url,q,r);if(p.modal==true){$.modal(element);}
return returnObject;},iDWordCount:function(p,q){var selector=$(this.selector);var display=$(p);selector.keypress(function()
{var numOfWords=selector.val().split(/[\s\.\?]+/).length;display.html(numOfWords);});},iDWorker:function(p,q){var p=(typeof p!='undefined')?p:{};var source=(typeof p.source!='undefined')?p.source:alert('Source needs to be defined.');var param=(typeof p.param!='undefined')?p.param:'';var myWorker=new Worker(source);myWorker.postMessage(param);myWorker.addEventListener('message',function(e){if(typeof q!='undefined'){q(e.data);}},false);return this;}});})(jQuery);window._$$=function(fn_name,fn){_$.prototype[fn_name]=fn;return this;};window._$=function(){return new _$(arguments);};$.iDAddslashes=function(p){var str=$.returnS(p);return(str+'').replace(/[\\"']/g,'\\$&').replace(/\u0000/g,'\\0');};$.iDAjax=function(p,lfn){var p=p;p['url']=(typeof p['url']!='undefined')?p['url']:'';p['type']=(typeof p['type']!='undefined')?p['type']:'POST';p['data']=(typeof p['data']!='undefined')?p['data']:'';p['dataType']=(typeof p['dataType']!='undefined')?p['dataType']:'json';$.ajax(p);return this;};$.iDBeforeUnload=function(q){if(typeof q!='undefined'&&typeof q=='object'){window.onbeforeunload=q;}else{window.onbeforeunload=function(e){return"You have attempted to leave this page.  If you have made any changes, your changes will be lost.  Are you sure you want to exit this page?";}}}
$.iDCropper=function(p,q){var p=$.returnObj(p);var src=$.returnObj(p.source);var s=$.returnEl(src.container);var rs=s.replace('#','');var sw=$.returnN(src.width);var sh=$.returnN(src.height);var si=$.returnS(src.image);var cw=$.returnN(src.cwidth);var tgt=$.returnObj(p.target);var ista=(typeof tgt.container=='object')?true:false;var t,rt,tw,th,cTw,cTh;if(ista){t=$.returnA(tgt.container);tw=$.returnA(tgt.width);th=$.returnA(tgt.height);}else{t=$.returnS(tgt.container);rt=t.replace('#','');tw=$.returnN(tgt.width);th=$.returnN(tgt.height);}
var o={};var now=new Date();var cid=now.getTime();var cnvsSrcId='cnvsSrc'+cid;var cnvsTgtId='cnvsTgt'+cid;var cnvsTgtIDs=new Array();var cnvsTgtCxt=new Array();var oImgs={};var cboxId='cropBox'+cid;o.source_id=cnvsSrcId;o.target_id=cnvsTgtId;o.cropbox_id=cboxId;$(s).css({width:sw+'px',height:sh+'px',overflow:'hidden',background:'#eee'});if(ista){for(e in t){cnvsTgtId+=e;$.iDEl({object:'canvas',parent:t[e],attribute:{id:cnvsTgtId,myclass:cnvsTgtId,width:tw[e]+'px',height:th[e]+'px'}});var tgtCxt=document.getElementById(cnvsTgtId).getContext('2d');tgtCxt.clearRect(0,0,tw[e],th[e]);cnvsTgtCxt.push(tgtCxt);cnvsTgtIDs.push(cnvsTgtId);cTw=(cw>0)?cw:tw[0];cTh=(cw>0)?cw:th[0];}}else{$.iDEl({object:'canvas',parent:t,attribute:{id:cnvsTgtId,myclass:cnvsTgtId,width:tw+'px',height:th+'px'}});var tgtCxt=document.getElementById(cnvsTgtId).getContext('2d');tgtCxt.clearRect(0,0,tw,th);cTw=tw;cTh=th;}
$.iDEl({object:'canvas',parent:s,attribute:{id:cboxId,myclass:cboxId,width:cTw+'px',height:cTh+'px',name:'cropBox'},style:{position:'absolute','z-index':10001,border:'2px dotted #5a5a5a'}});$.iDEl({object:'span',parent:s,attribute:{id:'lblwh',myclass:'lblwh'},style:{position:'absolute',height:'18px',background:'#000',color:'#fff','z-index':1},html:cTw+':'+cTh});var cropBox=document.getElementById(cboxId);var cropCxt=cropBox.getContext('2d');var cL,cT,siw,sih,srcImgL=0,srcImgT=0,cBP;var srcImgLoader=new Image();srcImgLoader.src=si;srcImgLoader.onload=function(){siw=srcImgLoader.width;sih=srcImgLoader.height;cT=$(s).offset().top;cL=$(s).offset().left;var cX2=siw-sw;var cY1=sh-sih+cT;var cX1=sw-siw+cL;var arrContainment;if(siw>sw&&sih>sh){arrContainment=[cX1,cY1,cL,cT];}else{arrContainment=[];}
var cnvsSrc=document.createElement('canvas');cnvsSrc.setAttribute('id',cnvsSrcId);cnvsSrc.setAttribute('width',siw+'px');cnvsSrc.setAttribute('height',sih+'px');$(s).append(cnvsSrc);var srcCxt=cnvsSrc.getContext('2d');srcCxt.drawImage(srcImgLoader,0,0,siw,sih,0,0,siw,sih);srcCxt.fillStyle="rgba(0,0,0,0.5)";srcCxt.fillRect(0,0,siw,sih);cropCxt.clearRect(0,0,cTw,cTh);cropCxt.drawImage(srcImgLoader,0,0,cTw,cTh,0,0,cTw,cTh);if(ista){for(e in cnvsTgtCxt){cnvsTgtCxt[e].clearRect(0,0,tw[e],th[e]);cnvsTgtCxt[e].drawImage(srcImgLoader,0,0,tw[e],th[e],0,0,tw[e],th[e]);}}else{tgtCxt.clearRect(0,0,cTw,cTh);tgtCxt.drawImage(srcImgLoader,0,0,cTw,cTh,0,0,cTw,cTh);}
cBP=$(s+' .ui-wrapper');$(cnvsSrc).draggable({cursor:'crosshair',containment:arrContainment,drag:function(e,ui){srcImgL=ui.position.left;srcImgT=ui.position.top;var x1=cBP.offset().left;var y1=cBP.offset().top;var x=-1*srcImgL+x1-cL;var y=-1*srcImgT+y1-cT;var w=cBP.width();var h=cBP.height();if(x*y>0){cropCxt.clearRect(0,0,w,h);cropCxt.drawImage(srcImgLoader,x,y,w,h,0,0,w,h);if(ista){for(e in cnvsTgtCxt){cnvsTgtCxt[e].clearRect(0,0,tw[e],th[e]);cnvsTgtCxt[e].drawImage(srcImgLoader,x,y,w,h,0,0,tw[e],th[e]);}}else{tgtCxt.clearRect(0,0,tw,th);tgtCxt.drawImage(srcImgLoader,x,y,w,h,0,0,tw,th);}}},stop:function(e,ui){srcImgL=ui.position.left;srcImgT=ui.position.top;if(ista){for(e in cnvsTgtIDs){try{oImgs[e]=document.getElementById(cnvsTgtIDs[e]).toDataURL();}catch(e){throw new Error("unable to access image data: "+e);}}
o.image=oImgs;}else{o.image=document.getElementById(cnvsTgtId).toDataURL();}
q(o);}});}
$(cropBox).resizable({handles:'all',resize:function(e,ui){var x1=$(ui.helper).parent().position().left;var y1=$(ui.helper).parent().position().top;var x=ui.position.left-x1-srcImgL;var y=ui.position.top-y1-srcImgT;var w=ui.size.width;var h=ui.size.height;cropBox.setAttribute('width',w+'px');cropBox.setAttribute('height',h+'px');if(x*y>0){cropCxt.drawImage(srcImgLoader,x,y,w,h,0,0,w,h);if(ista){for(e in cnvsTgtCxt){cnvsTgtCxt[e].clearRect(0,0,tw[e],th[e]);cnvsTgtCxt[e].drawImage(srcImgLoader,x,y,w,h,0,0,tw[e],th[e]);}}else{tgtCxt.clearRect(0,0,tw,th);tgtCxt.drawImage(srcImgLoader,x,y,w,h,0,0,tw,th);}
$('#lblwh').html(w+' : '+h);}},stop:function(e,ui){if(ista){for(e in cnvsTgtIDs){try{oImgs[e]=document.getElementById(cnvsTgtIDs[e]).toDataURL();}catch(e){throw new Error("unable to access image data: "+e);}}
o.image=oImgs;}else{o.image=document.getElementById(cnvsTgtId).toDataURL();}
q(o);}}).parent('.ui-wrapper').draggable({cursor:'crosshair',containment:'parent',drag:function(e,ui,srcCxt){var x1=ui.offset.left;var y1=ui.offset.top;var x=ui.offset.left-cL-srcImgL;var y=ui.offset.top-cT-srcImgT;var w=$(ui.helper).width();var h=$(ui.helper).height();if(x*y>0){cropCxt.clearRect(0,0,w,h);cropCxt.drawImage(srcImgLoader,x,y,w,h,0,0,w,h);if(ista){for(e in cnvsTgtCxt){cnvsTgtCxt[e].clearRect(0,0,tw[e],th[e]);cnvsTgtCxt[e].drawImage(srcImgLoader,x,y,w,h,0,0,tw[e],th[e]);}}else{tgtCxt.clearRect(0,0,cTw,cTh);tgtCxt.drawImage(srcImgLoader,x,y,w,h,0,0,cTw,cTh);}}},stop:function(e,ui){if(ista){for(e in cnvsTgtIDs){try{oImgs[e]=document.getElementById(cnvsTgtIDs[e]).toDataURL();}catch(e){throw new Error("unable to access image data: "+e);}}
o.image=oImgs;}else{o.image=document.getElementById(cnvsTgtId).toDataURL();}
q(o);}});$(s+' .ui-wrapper').css('z-index','10001');$(s+' .ui-wrapper .ui-icon').css({background:'rgba(255,255,255,0.5)',border:'2px dotted #5a5a5a'});if(ista){for(e in cnvsTgtIDs){oImgs[e]=document.getElementById(cnvsTgtIDs[e]).toDataURL();}
o.image=oImgs;}else{o.image=document.getElementById(cnvsTgtId).toDataURL();}
q(o);return this;};$.iDEl=function(p){var p=$.returnObj(p);var object=$.returnS(p.object,'div');var parent=$.returnS(p.parent);var target=$.returnS(p.target);var ptarget=target.replace(new RegExp("(\#|\.)"),"");var attribute=$.returnObj(p.attribute);var style=$.returnObj(p.style);var html=$.returnS(p.html);var event=$.returnObj(p.event);var id=$.returnS(p.id);var required=$.returnB(p.required,false);var el,oobject;var myclass;var warningBoxT,warningBoxL,warningBoxW,warningBoxH,warningText,hasbr,br=0;if(object=='button'){object='div';myclass='iDButton';}
else if(object=='checkbox'){object='input';myclass='iDCheckbox';attribute.type='checkbox';}
else if(object=='radio'){object='input';myclass='iDRadio';attribute.type='radio';}
else if(object=='text'){object='input'
myclass='iDText';attribute.type='text';}
else if(object=='textarea'){object='textarea';myclass='iDTextarea';}
else if(object=='warning'){warningText="<span id='iDWarnText_"+ptarget+"'>"+html+"</span>";oobject=object;object='div';myclass='iDWarning iDWarn_'+ptarget;$(target).click(function(){$('.iDWarn_'+ptarget).fadeOut();});}
else if(object=='confirm'){$('.iDConfirm').remove();oobject=object;object='div';myclass='iDConfirm';}
el=document.createElement(object);if(oobject=='warning'){hasbr=html.match(/\<br/gi);if(hasbr!=null){br=hasbr.length;}
warningBoxH=18+(18*br);if(br>0){warningBoxW=html.split('<br')[0].length*7;}else{warningBoxW=html.length*7;}
warningBoxT=$(target).offset().top-$(parent).offset().top;warningBoxL=$(parent).width()-10;el.style.cssText+="width:"+warningBoxW+"px;top:"+warningBoxT+"px;left:"+warningBoxL+"px;";}
el.innerHTML=(html!='')?html:'';if(id!=''){el.setAttribute('id',id);}
el.setAttribute('class',myclass);for(key in attribute){if(attribute.hasOwnProperty(key)){if(key=='myclass'){nKey='class';}else{nKey=key;}
el.setAttribute(nKey,attribute[key]);}}
var styleText='';for(key in style){if(style.hasOwnProperty(key)){styleText+=key+':'+style[key]+';';}}
if(styleText!=''){el.style.cssText+=styleText;}
$(p.parent).append(el);if(oobject=='confirm'){$.iDEl({object:'button',html:"Confirm",parent:'.iDConfirm',attribute:{id:'iDConfirm_confirm'},style:{margin:$('.iDConfirm').height()-50+'px 10px 10px 20px'}});$('#iDConfirm_confirm').bind('click',function(e){p.confirm(e);$('.iDConfirm').remove();});$.iDEL({object:'button',html:"Cancel",parent:'.iDConfirm',attribute:{id:'iDConfirm_cancel'},style:{margin:$('.iDConfirm').height()-50+'px 10px 10px 100px'}});$('#iDConfirm_cancel').bind('click',function(e){if(typeof p.cancel!='undefined'){p.cancel(e);}
$('.iDConfirm').remove();});$(el).draggable({containment:'parent',cursor:'move'});}
if(required){var boxT=$(el).position().top;var boxL=$(el).position().left;var reqT=boxT+5;var reqL=boxL-10;var reqStar=document.createElement('span');reqStar.setAttribute('class','iDRequired');reqStar.style.cssText="position:absolute;top:"+reqT+"px;left:"+reqL+"px;";reqStar.innerHTML="*";$(parent).append(reqStar);}
for(key in event){if(event.hasOwnProperty(key)){}}
return this;};$.iDFadeInOut=function(p){var p=$.returnObj(p);var fin=$.returnS(p.fin);var fout=$.returnS(p.fout);var dur=$.returnN(p.dur);var btn=$.returnS(p.btn);myfin=fin;myfout=fout;myfdur=dur;$(fout).fadeOut(dur,function(){$(this).hide();$(fin).show();$(btn).click(function(){if(typeof p.stay=='function'){p.stay();}else{$(fin).fadeOut(dur,function(){$(fin).hide();$(fout).show();myfin=myfout='';myfdur=500;});}})});return this;};$.iDFadeOutIn=function(fin,fout,dur){$(myfin).fadeOut(myfdur,function(){$(myfin).hide();$(myfout).fadeIn().show();myfin=myfout='';myfdur=500;});return this;};$.iDLoadJS=function(p,q){var p=((typeof p=='string'&&p!=null)||(typeof p=='object'&&typeof p!='undefined'))?p:null;var url=(typeof p=='string'&&p!=null)?p:(typeof p.url!='undefined')?p.url:alert('A source url needs to be defined.');var parent=(typeof p.parent!='undefined')?p.parent:'body';var script=document.createElement("script")
script.type="text/javascript";if(script.readyState){script.onreadystatechange=function(){if(script.readyState=="loaded"||script.readyState=="complete"){script.onreadystatechange=null;if(typeof q!='undefined'){q();}}};}else{script.onload=function(){if(typeof q!='undefined'){q();}};}
script.src=url;var el;if(parent=='body'){el=document.getElementsByTagName(parent);el[el.length-1].appendChild(script);}else{$("'"+parent+"'").append(script);}
return this;};$.iDNoti=function(m,p,q){$('#notiPanel').remove();var p=(typeof m=='object')?m:(typeof p!='undefined')?p:{}
var m=(typeof m=='string')?m:'';var myClass=(typeof p.myclass!='undefined')?p.myclass:'iDNotifier';var attribute=(typeof p.attribute!='undefined')?p.attribute:{};var style=(typeof p.style!='undefined')?p.style:{};var html=((typeof p.html)!='undefined')?p.html:{};var parent=(typeof p.parent!='undefined')?p.parent.match('#')?p.parent:'#'+p.parent:'body';var event=(typeof p.event!='undefined')?p.event:{};var timeout=(typeof p.timeout!='undefined')?p.timeout:2000;var winH=$(window).height();var winW=$(window).width();var el=document.createElement('div');var notiW=250;var notiH=100;var notiT=winH-notiH-40;var notiL=winW-notiW-150;el.style.cssText+='display:none;top:'+winH+'px;left:'+notiL+'px;';el.setAttribute('id','notiPanel');if(typeof p.myclass=='undefined'){el.style.cssText+='background:rgba(103,167,227,1);position:absolute;width:'+notiW+'px;height:'+notiH+'px;z-index:9999;padding:20px;font:1.4em bold;color:#fff;';}
el.className=myClass;for(key in attribute){if(attribute.hasOwnProperty(key)){if(key=='myclass'){nKey='class';}else{nKey=key;}
el.setAttribute(nKey,attribute[key]);}}
var styleText='';for(key in style){if(style.hasOwnProperty(key)){styleText+=key+':'+style[key]+';';}}
el.style.cssText+=styleText;for(key in event){if(event.hasOwnProperty(key)){el.addEventListener(key,event[key],false);}}
el.innerHTML=(m!='')?m:html;$('body').append(el);$(el).css('display','block').animate({top:notiT+'px'},500);setTimeout("this.fadeDown()",timeout);fadeDown=function(){$('#notiPanel').animate({top:winH+'px'},1000,function(){$(this).remove();});}};$.iDProgressorEnd=function(p){$('.iDPreloader').remove();return this;};$.iDProgressorInit=function(p){var p=(typeof p!='undefined')?p:'';var container=(typeof p.container!='undefined')?p.container:'body';var top=(typeof p.top!='undefined')?p.top:0;var left=(typeof p.left!='undefined')?p.left:0;var width=(typeof p.width!='undefined')?p.width:120;var height=(typeof p.height!='undefined')?p.height:120;;var alpha=(typeof p.alpha!='undefined')?p.alpha:1;var source=(typeof p.source!='undefined')?p.source:iDRootR+'default/progressor.gif';var time=(typeof p.time!='undefined')?p.time:1;var ptop=$(container).offset().top+($(container).height()-height)/2+top;var pleft=$(container).offset().left+($(container).width()-width)/2+left;$(container).append('<div class=\'iDPreloader\' style=\'position:absolute;top:'+ptop+'px;left:'+pleft+'px;\' ><img src="'+source+'"  /></div>');this.timer=setTimeout(function(){if(typeof p.success=='function'){p.success();}},time);return this;};$.iDRenders=function(url,arguments,callback){for(var d in arguments){sessionStorage.setItem(d,arguments[d]);}
location.href=url;callback&&callback();return this;};$.iDResizer=function(p,q){var p=$.returnObj(p);var s=$.returnS(p.source);var w=$.returnN(p.width,0);var h=$.returnN(p.height,0);var k=$.returnB(p.shrink,false);var siw,sih,tw,th,wh,wG,hG,rO,o={};var myImgLoader=new Image();myImgLoader.src=s;myImgLoader.onload=function(){siw=myImgLoader.width;sih=myImgLoader.height;wG=siw-w;hG=sih-h;if(k==true){wh=(w>0)?w:h;if(siw>sih){r=sih/siw;tw=wh;th=r*tw;}
else if(sih>siw){r=siw/sih;th=wh;tw=r*th;}else{tw=th=wh;}}else{if(w>0&&h>0){tw=w;th=h;}
else if(w>0){tw=w;th=(sih*w)/siw;}
else if(h>0){th=h;tw=(siw*h)/sih;}}
var cnvsSrc=document.createElement('canvas');cnvsSrc.setAttribute('width',tw+'px');cnvsSrc.setAttribute('height',th+'px');var srcCxt=cnvsSrc.getContext('2d');srcCxt.drawImage(myImgLoader,0,0,siw,sih,0,0,tw,th);o.width=siw;o.height=sih;o.output_width=tw;o.output_height=th;o.image=cnvsSrc.toDataURL();q(o);};return this;};$.iDYesNo=function(p,q){var title=$.returnS(p.title,'Delete');var message=$.returnS(p.message,'Are you sure?');$("<div class='iDYesNoDialog'></div>").appendTo('body').html('<span><h6>'+message+'</h6></span>').dialog({modal:true,title:title,zIndex:10000,autoOpen:true,width:'auto',resizable:false,buttons:{Yes:function(){q();$(this).dialog("close");},No:function(){$(this).dialog('close');}},close:function(event,ui){$(this).remove();}});return this;};$.iDStripHtml=function(html){var tmp=document.createElement("div");tmp.innerHTML=html;return tmp.textContent||tmp.innerText;};$.iDStripslashes=function(p){var str=$.returnS(p);return(str+'').replace(/\\(.?)/g,function(s,n1){switch(n1){case'\\':return'\\';case'0':return'\u0000';case'':return'';default:return n1;}});};$.iDView=function(p,q,r){var p=(typeof p!='undefined')?p:{};var url=(typeof p.url!='undefined')?p.url:alert('url needs to be defined.');var parent=(typeof p.id!='undefined')?(p.id.match('#'))?p.id:'#'+p.id:alert('View needs its own id.');var container=(typeof p.container!='undefined')?(p.container.match('#'))?p.container:'#'+p.container:'';var attribute=(typeof p.attribute!='undefined')?p.attribute:'';var style=(typeof p.style!='undefined')?p.style:'';var el=(typeof p.element!='undefined')?p.element:'div';var element;$(parent).remove();element=document.createElement(el);element.setAttribute('id',parent.replace("#",''));element.style.cssText='display:none';$(element).load(url,q,r);for(key in attribute){if(attribute.hasOwnProperty(key)){if(key=='myclass'){nKey='class';}else{nKey=key;}
element.setAttribute(nKey,attribute[key]);}}
var styleText='';for(key in style){if(style.hasOwnProperty(key)){styleText+=key+':'+style[key]+';';}}
if(styleText!=''){element.style.cssText=styleText;}
var appender;if(container!=''){appender=container;}else{appender='body';}
var returnObject=$(appender).append(element);if(p.modal==true){this.iDModal(element);}
return returnObject;};$.returnA=function(p,q){var myp=(typeof p!='undefined')?p:(typeof q!='undefined')?q:[];return myp;};$.returnArray=function(p,q){$.returnA(p,q);};$.returnB=function(p,q){var myp=(typeof p!='undefined')?p:(typeof q!='undefined')?q:false;return myp;};$.returnBoolean=function(p,q){$.returnB(p,q);};$.returnEl=function(p,q){var myp=(typeof p!='undefined')?p.match('#')?p:'#'+p:(typeof q!='undefined')?alert(q):alert('The element to show needs to be defined');return myp;};$.returnElment=function(p,q){$.returnEl(p,q);};$.returnN=function(p,q){var myp=(typeof p!='undefined')?p:(typeof q!='undefined')?q:0;return myp;};$.returnNumber=function(p,q){$.returnN(p,q);};$.returnObj=function(p,q){var myp=(typeof p!='undefined')?p:(typeof q!='undefined')?q:{};return myp;};$.returnObject=function(p,q){$.returnObj(p,q);};$.returnP=function(p){var myp=((typeof p=='string'&&p!=null)||(typeof p=='object'&&typeof p!='undefined'))?p:null;return myp;};$.returnParameter=function(p){$.returnP(p);};$.returnS=function(p,q){var myp=(typeof p!='undefined')?p:(typeof q!='undefined')?q:'';return myp;};$.returnString=function(p,q){$.returnS(p,q);};};